# Generated by Django 5.2.14 on 2026-05-28 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0002_alter_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField()),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('peak_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pending_buybacks', models.JSONField(default=list)),
                ('initial_shares', models.IntegerField()),
                ('initial_avg_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('trailing_stop_pct', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('buyback_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('min_hold_pct', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('fee_pct', models.DecimalField(decimal_places=4, default=0.0305, max_digits=6)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('tracking_started_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('SELL', 'Venda'), ('BUY', 'Recompra')], max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=10)),
                ('suggested_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('shares', models.IntegerField()),
                ('peak_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('profit_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_price_ref', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('buyback_trigger', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('profit_captured', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pending_buyback_id', models.CharField(blank=True, max_length=16, null=True)),
                ('sell_ref_date', models.CharField(blank=True, max_length=12, null=True)),
                ('buy_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('saved', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('shares_after', models.IntegerField(blank=True, null=True)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
